name: CI                           # The workflow’s name (you'll see it in the Actions tab)

on:                                # When to trigger the workflow
  pull_request:                    # Runs for every PR (feature → main)
  push:                            # And for direct pushes to main
    branches: [ main ]

jobs:                              # A workflow can have multiple jobs; we have one called "test"
  test:
    runs-on: ubuntu-latest         # GitHub spins up a clean Linux VM for this job
    steps:                         # Steps run in order; any step failing stops the job
      - uses: actions/checkout@v4  # 1) Pulls your repo code into the VM
      - uses: actions/setup-python@v5   # 2) Installs Python into the VM
        with:
          python-version: "3.11"
      - run: python -m pip install -r requirements.txt   # 3) Install test deps (pytest)
      - run: pytest -q                 # 4) Run tests; exit code decides pass/fail

